### ISSUE TITLE
centos6/7 comile error

### ISSUE THREAD

**Issue by Bepartofyou** [NATTools/stunlib#16]
Hi : I want to learn stun/turn/ICE protocol with your libs. may you modify this error, thanks!

I just git clone the sourcecode and exec build.sh and errors like this:

stunlib/src/stunlib.c:13:24: error: bsd/stdlib.h: No such file or directory
cc1: warnings being treated as errors
stunlib/src/stunlib.c: In function ‘stunlib_createId’:
stunlib/src/stunlib.c:3396: error: implicit declaration of function ‘arc4random_buf’
At top level:
cc1: error: unrecognized command line option "-Wno-gnu-zero-variadic-macro-arguments"
make[2]: *** [src/CMakeFiles/stunlib.dir/stunlib.c.o] Error 1
make[1]: *** [src/CMakeFiles/stunlib.dir/all] Error 2
make: *** [all] Error 2

**Comment by Bepartofyou** [comment]
So sorry for borthering you, I have solved this error with 'yum install libbsd libbsd-devel'.

**Comment by palerikm** [comment]
No worries. Should probably have some better cmake files to detect if it is missing from your system.
