### ISSUE TITLE
Make it more embedded-friendly?

### ISSUE THREAD

**Issue by SStorm** [NATTools/stunlib#17]
Hi guys, would you consider a PR that makes the dependencies on zlib and openssl optional? This would make it easier to use the library in embedded scenarios, i.e. with mbedTLS.

**Comment by palerikm** [comment]
Sorry for late reply.

That sounds like av interesting PR.

**Comment by SStorm** [comment]
Pull request #18, happy to discuss implementation details!

**Comment by palerikm** [comment]
That was a good addition. Merged!
